### ISSUE TITLE
Group 'gpio' doesnt work without sudo

### ISSUE THREAD

**Issue by jshaker000** [TheNextLVL/RPi.GPIO.64#2]
Im not sure if this is a Kernel issue or not.  
I am running on the raspberry pi 3B+ archlinux arm64 and am required to run all gpio commands with sudo.
Doing some research it seems that the issue is that the GPIO service will use /dev/gpiomem if it exists, otherwise it will use /dev/mem. My pi does not have /dev/gpiomem

I believe the distinction is made so that everyone in gpio can see only the gpio registers without reading all of RAM?

Is this something you can fix or adjust on your end or should I email the distro maintainer?

**Comment by TheNextLVL** [comment]
This is related to the kernel. When I tested the archlinux for rpi3b last time (SEP-18) have this same issue. 
I dont't know which kernel is using archlinux, but the other SO that uses the 64bit kernel from rpi official repo creates the /dev/gpiomem. 
You can try to use the [kernel from sakaki](https://github.com/sakaki-/bcmrpi3-kernel) as i suggested in the readme of this project. Just follow the instructions on the [Installation](https://github.com/sakaki-/bcmrpi3-kernel#installation) section. I have test this kernel with the Pi64OS and RPi-arm64
 Debian from UMRnInside and works great.

After installing the kernel you will see the /dev/gpiomem in your SO. Don't forgive to check the permissions of this file. It should by `crw-rw----` and belongs and belongs to `root:gpio`. 
To do that just create a file in `/etc/udev/rules.d/60-gpiomem.rules` with:
```
SUBSYSTEM=="gpio*", PROGRAM="/bin/sh -c 'chown -R root:gpio /sys/class/gpio && chmod -r 770 /sys/class/gpio; chown -R root:gpio /sys/devices/virtual/gpio && chmod -R 770 /sys/devices/virtual/gpio; chown -R root:gpio /sys/devices/platform/soc/*.gpio/gpio && chmod -R 770 /sys/devices/platform/soc/*.gpio/gpio'"
SUBSYSTEM=="bcm2835-gpiomem", GROUP="gpio", MODE="0660"
```

**Comment by jshaker000** [comment]
Thanks, I will try installing that Kernel.  
As a seperate issue, related to the last one I raised, my other raspberry pi's content of
/proc/device-tree/model  is 'Raspberry Pi 3 Model B'
rather than 'Raspberry Pi 3 Model B+'
and therefore the hotfix you made in january isnt working for him. Could you add that usecase?  
I wish all this was more standardized. I appreciate your help!

**Comment by TheNextLVL** [comment]
Hi @jshaker000, I just updated adding support for RPi3B using archlinux. Try it and let me know if thre is any bug.

**Comment by TheNextLVL** [comment]
I guess you've solved your problem, closing the issue.
